name: CI

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: gpu-test
    container:
      image: beehivelab/tornadovm-nvidia-openjdk:latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew -Pbabylonml.tornadovm.home=/tornado/tornado/bin/sdk build

    
