name: CI

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: gpu-test

    steps:
    # - name: Fix environment
    #   run: |
    #     echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'  # Use a compatible Node.js version

    - name: Pull Docker Image
      run: docker pull beehivelab/tornadovm-nvidia-openjdk:1.0.6
      
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew -Pbabylonml.tornadovm.home=/tornado/tornado/bin/sdk build

    
